---
title: "Accessing data from Single-Cell Expression Atlas"
author: "Pedro Madrigal"
affiliation: "EMBL-EBI"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: false
    toc_depth: 3
    number_sections: false
bibliography: references.bib
keywords: ["gene expression", "RNA-seq", "ExpressionAtlas", "Bioconductor", "single-cell"]
vignette: >
    %\VignetteEngine{ knitr::rmarkdown }
    %\VignetteBuilder{ knitr }
    %\VignetteIndexEntry{ Accessing data from Single-Cell Expression Atlas }
    %\VignetteEncoding{UTF-8}
---


This vignette demonstrates how to access and visualise dataset [E-GEOD-81383](https://www.ebi.ac.uk/gxa/sc/experiments/E-GEOD-81383) from the 
Single-Cell Expression Atlas using the `ExpressionAtlas` package. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
```
```{r}
library( ExpressionAtlas ) 
library( SingleCellExperiment )
library( ggplot2 )
```

```{r eval=TRUE}
sc_search_results <- searchSCAtlasExperiments( query = "hematopoietic", secondaryFilter = "old" )
print(sc_search_results)

geod81383 <- getAtlasSCExperiment( "E-GEOD-81383" )
geod81383

print("Reduced dimension names:")
print(reducedDimNames(geod81383 ))

print("Column data names:")
print(colnames(colData(geod81383 )))

plotDimRedSCAtlasExperiment(geod81383, dimRed = "X_umap_neighbors_n_neighbors_20", colorby = "louvain_resolution_0.1") + theme_classic() 

# plotDimRedSCAtlasExperiment(geod81383, dimRed = "X_umap_neighbors_n_neighbors_20", colorby = "genotype") + theme_classic() 

plotDimRedSCAtlasExperiment(geod81383, dimRed = "X_umap_neighbors_n_neighbors_20", colorby = "age") + theme_classic() + scale_colour_brewer(palette = "Set2")

plotDimRedSCAtlasExperiment(geod81383, dimRed = "X_umap_neighbors_n_neighbors_20", colorby = "cell_line") + theme_classic() + scale_colour_brewer(palette = "Accent")


# heatmapSCAtlasExperiment(geod81383, genes=NULL, sel.K=5, scaleNormExp=FALSE, show_row_names=FALSE ) 

heatmapSCAtlasExperiment(geod81383, genes=NULL, sel.K=3, scaleNormExp=TRUE, show_row_names=FALSE ) 

dotPlotSCAtlasExperiment(geod81383, genes=c('ENSG00000185664', 'ENSG00000205777', 'ENSG00000135218'), sel.K=3, scaleNormExp=TRUE) + theme_classic()

# dotPlotSCAtlasExperiment(geod81383, genes=c('ENSG00000185664', 'ENSG00000205777', 'ENSG00000135218', 'ENSMUSG00000048442'), sel.K=6, scaleNormExp=FALSE) + theme_classic()

```

# sessionInfo

```{r}
sessionInfo()
```

